### ISSUE TITLE
pip3 install coincurve

### ISSUE THREAD

**Issue by taylorgag** [ofek/coincurve#100]
Sorry to bother you, when I use the command **pip3 install coincurve**,its outputs are :
pip3 install coincurve
Collecting coincurve
  Using cached https://files.pythonhosted.org/packages/49/62/742ea42846d4250c9e3503e791b2906ede13d51fae09076802d9e96f466c/coincurve-15.0.1.tar.gz
Collecting asn1crypto (from coincurve)
  Using cached https://files.pythonhosted.org/packages/b5/a8/56be92dcd4a5bf1998705a9b4028249fe7c9a035b955fe93b6a3e5b829f8/asn1crypto-1.4.0-py2.py3-none-any.whl
Collecting cffi>=1.3.0 (from coincurve)
  Using cached https://files.pythonhosted.org/packages/f2/cd/3f5f059fed635d71047fa9ce507635088f982ab280fc24cde91d9afb9c1c/cffi-1.14.6-cp36-cp36m-manylinux1_x86_64.whl
Collecting pycparser (from cffi>=1.3.0->coincurve)
  Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
Building wheels for collected packages: coincurve
  Running setup.py bdist_wheel for coincurve ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p3onnz6f/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpmu3f4qylpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/types.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/context.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/__init__.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/_windows_libsecp256k1.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/utils.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/keys.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/flags.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/ecdsa.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/py.typed -> build/lib.linux-x86_64-3.6/coincurve
  running build_clib
  /tmp/pip-build-p3onnz6f/coincurve/libsecp256k1/autogen.sh: 3: /tmp/pip-build-p3onnz6f/coincurve/libsecp256k1/autogen.sh: autoreconf: not found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-p3onnz6f/coincurve/setup.py", line 309, in <module>
      **setup_kwargs
    File "/home/wbb/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-p3onnz6f/coincurve/setup.py", line 95, in run
      _bdist_wheel.run(self)
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-p3onnz6f/coincurve/setup.py", line 152, in run
      subprocess.check_call([autogen], cwd=absolute('libsecp256k1'))
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/tmp/pip-build-p3onnz6f/coincurve/libsecp256k1/autogen.sh']' returned non-zero exit status 127.
  
  ----------------------------------------
  Failed building wheel for coincurve
  Running setup.py clean for coincurve
Failed to build coincurve
Installing collected packages: asn1crypto, pycparser, cffi, coincurve
  Running setup.py install for coincurve ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p3onnz6f/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-47pj8ydb-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/types.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/context.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/__init__.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/_windows_libsecp256k1.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/utils.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/keys.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/flags.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/ecdsa.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/py.typed -> build/lib.linux-x86_64-3.6/coincurve
    running build_clib
    /tmp/pip-build-p3onnz6f/coincurve/libsecp256k1/autogen.sh: 3: /tmp/pip-build-p3onnz6f/coincurve/libsecp256k1/autogen.sh: autoreconf: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-p3onnz6f/coincurve/setup.py", line 309, in <module>
        **setup_kwargs
      File "/home/wbb/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/wbb/.local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-p3onnz6f/coincurve/setup.py", line 152, in run
        subprocess.check_call([autogen], cwd=absolute('libsecp256k1'))
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-p3onnz6f/coincurve/libsecp256k1/autogen.sh']' returned non-zero exit status 127.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p3onnz6f/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-47pj8ydb-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-p3onnz6f/coincurve/

**Comment by taylorgag** [comment]
Well, actually, I upgrade the version of pip3  and it works.

**Comment by ofek** [comment]
I'm glad it's working for you now
