### ISSUE TITLE
Can't handle large number?

### ISSUE THREAD

**Issue by ryanjsfx2424** [ofek/coincurve#122]
I receive the same output for two specific inputs for the following:

```
from coincurve import PublicKey
num = 2**256-1
p0 = PublicKey.from_valid_secret(hex(num).encode()).format(compressed=False)[1:]
p1 = PublicKey.from_valid_secret(hex(num-1).encode()).format(compressed=False)[1:]
print("p0 == p1: ", p0 == p1)
```

Maybe this is correct but I would've thought two different secrets would generate two different public keys.

As for why I'm doing this, I wanted to learn how secp256k1 works and ideally in Python -- but it looks like I'm off to C. I thought I'd share here in case this points to a problem handling large numbers.

**Comment by ofek** [comment]
That's an invalid secret:

```pycon
>>> from coincurve import PublicKey
>>> from coincurve.utils import int_to_bytes
>>>
>>> PublicKey.from_secret(int_to_bytes(2**256-1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\ofek\desktop\code\coincurve\coincurve\keys.py", line 332, in from_secret
    created = lib.secp256k1_ec_pubkey_create(context.ctx, public_key, validate_secret(secret))
  File "c:\users\ofek\desktop\code\coincurve\coincurve\utils.py", line 91, in validate_secret
    raise ValueError('Secret scalar must be greater than 0 and less than {}.'.format(GROUP_ORDER_INT))
ValueError: Secret scalar must be greater than 0 and less than 115792089237316195423570985008687907852837564279074904382605163141518161494337.
```
