### ISSUE TITLE
Latest release broke installation under Windows

### ISSUE THREAD

**Issue by darosior** [ofek/coincurve#133]
I'm using Coincurve in my BIP32 package. Following a request from @MementoRC i was in the process of bumping the maximum supported Coincurve version to `0.19` (https://github.com/darosior/python-bip32/pull/40) when my CI caught that installing Coincurve under Windows was broken (see [here](https://github.com/darosior/python-bip32/blob/1492d39312f1d9630363c292f6ab8beb8ceb16dd/.github/workflows/python-package.yml#L28-L31) for the installation instructions).

First of all, `cffi` was missing. Adding a temporary commit to manually install `cffi` to make sure it was the only issue revealed at runtime that Coincurve wasn't correctly installed (see [here](https://github.com/darosior/python-bip32/actions/runs/7623231539/job/20762850575?pr=40) for the CI job):
```
Traceback (most recent call last):
  File "D:\a\python-bip32\python-bip32\setup.py", line 2, in <module>
    import bip32
  File "D:\a\python-bip32\python-bip32\bip32\__init__.py", line 1, in <module>
    from .bip32 import BIP32, PrivateDerivationError, InvalidInputError
  File "D:\a\python-bip32\python-bip32\bip32\bip32.py", line 5, in <module>
    from .utils import (
  File "D:\a\python-bip32\python-bip32\bip32\utils.py", line 1, in <module>
    import coincurve
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\coincurve\__init__.py", line 1, in <module>
    from coincurve.context import GLOBAL_CONTEXT, Context
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\coincurve\context.py", line 5, in <module>
    from coincurve.flags import CONTEXT_ALL, CONTEXT_FLAGS
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\coincurve\flags.py", line 3, in <module>
    CONTEXT_SIGN = lib.SECP256K1_CONTEXT_SIGN
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\cffi\api.py", line 912, in __getattr__
    make_accessor(name)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\cffi\api.py", line 907, in make_accessor
    raise AttributeError(name)
AttributeError: SECP256K1_CONTEXT_SIGN
```

**Comment by ofek** [comment]
@MementoRC

**Comment by MementoRC** [comment]
@ofek @darosior Started to look at it

**Comment by ecy777** [comment]
I'm having the same problem too

**Comment by ofek** [comment]
Yanked:

![image](https://github.com/ofek/coincurve/assets/9677399/61b0d8b6-7b52-437b-8250-1837d30c87ce)

**Comment by MementoRC** [comment]
@ofek The issue must be with the `_windows_libsecp256k1.py`. It is unclear how all the tests on windows for the conda feedstock did not highlight this issue if CFFI does not handle `#define (formulae)` correctly. I ran all the coincurve tests successfully for the feedstock
I proposed a PR: https://github.com/ofek/coincurve/pull/135

It includes more than just the windows fix, please review and let me know if you prefer to separate it

**Comment by darosior** [comment]
Hey there, any update on this issue?

**Comment by ofek** [comment]
Fixed: https://github.com/ofek/coincurve/releases/tag/v19.0.1
