### ISSUE TITLE
coincurve-17.0.0 fails to install (macOS python 3.11.8)

### ISSUE THREAD

**Issue by mdragoss** [ofek/coincurve#168]
Collecting eciespy==0.3.13
  Using cached eciespy-0.3.13-py3-none-any.whl.metadata (13 kB)
Collecting coincurve<18,>=13 (from eciespy==0.3.13)
  Using cached coincurve-17.0.0.tar.gz (2.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      running dist_info
      creating /private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-modern-metadata-nqqa31sx/coincurve.egg-info
      writing /private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-modern-metadata-nqqa31sx/coincurve.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-modern-metadata-nqqa31sx/coincurve.egg-info/dependency_links.txt
      writing requirements to /private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-modern-metadata-nqqa31sx/coincurve.egg-info/requires.txt
      writing top-level names to /private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-modern-metadata-nqqa31sx/coincurve.egg-info/top_level.txt
      writing manifest file '/private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-modern-metadata-nqqa31sx/coincurve.egg-info/SOURCES.txt'
      reading manifest file '/private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-modern-metadata-nqqa31sx/coincurve.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file '/private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-modern-metadata-nqqa31sx/coincurve.egg-info/SOURCES.txt'
      creating '/private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-modern-metadata-nqqa31sx/coincurve-17.0.0.dist-info'
      Traceback (most recent call last):
        File "projects/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "projects/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "projects/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-build-env-654rhl6w/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 368, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-build-env-654rhl6w/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-build-env-654rhl6w/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 264, in <module>
        File "/private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-build-env-654rhl6w/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-build-env-654rhl6w/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-build-env-654rhl6w/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-build-env-654rhl6w/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-build-env-654rhl6w/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 976, in run_command
          super().run_command(command)
        File "/private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-build-env-654rhl6w/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-build-env-654rhl6w/overlay/lib/python3.11/site-packages/setuptools/command/dist_info.py", line 97, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-build-env-654rhl6w/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 302, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/61/fw6nrmz13kg8_506brzjdsfw0000gn/T/pip-build-env-654rhl6w/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 862, in get_command_obj
          cmd_obj = self.command_obj[command] = klass(self)
                                                ^^^^^^^^^^^
      TypeError: 'NoneType' object is not callable
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by ofek** [comment]
What happened?

**Comment by mdragoss** [comment]
messed up Python version
