### ISSUE TITLE
Undefined reference to `ECDSA_SIG_get0'

### ISSUE THREAD

**Issue by ghost** [ofek/coincurve#28]
When trying to install the most recent versions of Coincurve, as part of pyethereum, in a docker image (https://hub.docker.com/r/seegno/bitcoind/) and with DockerFile (https://github.com/blockchain-certificates/cert-issuer/blob/master/Dockerfile), I get the following error and log: 

```
pip install coincurve==8.0.0
Collecting coincurve==8.0.0
  Downloading https://files.pythonhosted.org/packages/9f/42/4edb5e3abceade4ba8aa1df0f0aec2700a2187282ea6530fd0c7aae23140/coincurve-8.0.0.tar.gz (914kB)
    100% |████████████████████████████████| 921kB 5.3MB/s 
Requirement already satisfied: asn1crypto in /usr/lib/python3.6/site-packages (from coincurve==8.0.0) (0.24.0)
Requirement already satisfied: cffi>=1.3.0 in /usr/lib/python3.6/site-packages (from coincurve==8.0.0) (1.11.5)
Requirement already satisfied: pycparser in /usr/lib/python3.6/site-packages (from cffi>=1.3.0->coincurve==8.0.0) (2.19)
Installing collected packages: coincurve
  Running setup.py install for coincurve ... error
    Complete output from command /usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xcal62qa/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1dl643vp/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/utils.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/ecdsa.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/_windows_libsecp256k1.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/__init__.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/keys.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/context.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/flags.py -> build/lib.linux-x86_64-3.6/coincurve
    creating build/lib.linux-x86_64-3.6/tests
    copying tests/test_ecdsa.py -> build/lib.linux-x86_64-3.6/tests
    copying tests/test_utils.py -> build/lib.linux-x86_64-3.6/tests
    copying tests/__init__.py -> build/lib.linux-x86_64-3.6/tests
    copying tests/samples.py -> build/lib.linux-x86_64-3.6/tests
    copying tests/test_keys.py -> build/lib.linux-x86_64-3.6/tests
    running build_clib
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /tmp/pip-install-xcal62qa/coincurve/libsecp256k1/build-aux/install-sh -c -d
    checking for gawk... no
    checking for mawk... no
    checking for nawk... no
    checking for awk... awk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking how to print strings... printf
    checking for style of include used by make... GNU
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking dependency style of gcc... none
    checking for a sed that does not truncate output... /bin/sed
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for fgrep... /bin/grep -F
    checking for ld used by gcc... /usr/x86_64-alpine-linux-musl/bin/ld
    checking if the linker (/usr/x86_64-alpine-linux-musl/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 98304
    checking whether the shell understands some XSI constructs... yes
    checking whether the shell understands "+="... yes
    checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/x86_64-alpine-linux-musl/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    /tmp/pip-install-xcal62qa/coincurve/libsecp256k1/configure: line 6421: /usr/bin/file: No such file or directory
    checking for mt... no
    checking if : is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/x86_64-alpine-linux-musl/bin/ld) supports shared libraries... yes
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... no
    checking whether to build static libraries... yes
    checking whether make supports nested variables... (cached) yes
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for ar... /usr/bin/ar
    checking for ranlib... /usr/bin/ranlib
    checking for strip... /usr/bin/strip
    checking for gcc... gcc
    checking whether we are using the GNU C compiler... (cached) yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... (cached) none needed
    checking whether gcc understands -c and -o together... (cached) yes
    checking dependency style of gcc... (cached) none
    checking how to run the C preprocessor... gcc -E
    checking for gcc option to accept ISO C89... (cached) none needed
    checking dependency style of gcc... none
    checking if gcc supports -std=c89 -pedantic -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -Wno-unused-function -Wno-long-long -Wno-overlength-strings... yes
    checking if gcc supports -fvisibility=hidden... yes
    checking for __int128... yes
    checking for __builtin_expect... yes
    checking native compiler: gcc... ok
    checking for x86_64 assembly availability... yes
    checking gmp.h usability... yes
    checking gmp.h presence... yes
    checking for gmp.h... yes
    checking for __gmpz_init in -lgmp... yes
    checking for CRYPTO... yes
    checking for main in -lcrypto... yes
    checking for EC functions in libcrypto... yes
    checking whether byte ordering is bigendian... no
    configure: Using static precomputation: yes
    configure: Using assembly optimizations: x86_64
    configure: Using field implementation: 64bit
    configure: Using bignum implementation: gmp
    configure: Using scalar implementation: 64bit
    configure: Using endomorphism optimizations: no
    configure: Building benchmarks: no
    configure: Building for coverage analysis: no
    configure: Building ECDH module: yes
    configure: Building ECDSA pubkey recovery module: yes
    configure: Using jni: no
    configure: ******
    configure: WARNING: experimental build
    configure: Experimental features do not have stable APIs or properties, and may not be safe for production use.
    configure: Building ECDH module: yes
    configure: ******
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating libsecp256k1.pc
    config.status: creating src/libsecp256k1-config.h
    config.status: executing depfiles commands
    config.status: executing libtool commands
    gcc -I/tmp/pip-install-xcal62qa/coincurve/libsecp256k1 -g -O2 -Wall -Wextra -Wno-unused-function -c /tmp/pip-install-xcal62qa/coincurve/libsecp256k1/src/gen_context.c -o gen_context.o
    gcc gen_context.o -o gen_context
    ./gen_context
      CC       src/libsecp256k1_la-secp256k1.lo
      CCLD     libsecp256k1.la
    /usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
      CC       src/tests-tests.o
    /tmp/pip-install-xcal62qa/coincurve/libsecp256k1/src/tests.c: In function 'test_ecdsa_der_parse':
    /tmp/pip-install-xcal62qa/coincurve/libsecp256k1/src/tests.c:4267:9: warning: implicit declaration of function 'ECDSA_SIG_get0' [-Wimplicit-function-declaration]
             ECDSA_SIG_get0(sig_openssl, &r, &s);
             ^~~~~~~~~~~~~~
    /tmp/pip-install-xcal62qa/coincurve/libsecp256k1/src/tests.c:4267:9: warning: nested extern declaration of 'ECDSA_SIG_get0' [-Wnested-externs]
    In file included from /tmp/pip-install-xcal62qa/coincurve/libsecp256k1/src/secp256k1.c:15:0,
                     from /tmp/pip-install-xcal62qa/coincurve/libsecp256k1/src/tests.c:17:
    /tmp/pip-install-xcal62qa/coincurve/libsecp256k1/src/ecmult_const_impl.h: In function 'secp256k1_wnaf_const.constprop':
    /tmp/pip-install-xcal62qa/coincurve/libsecp256k1/src/ecmult_const_impl.h:113:20: warning: 'u' may be used uninitialized in this function [-Wmaybe-uninitialized]
         wnaf[word] = u * global_sign;
                      ~~^~~~~~~~~~~~~
      CCLD     tests
    src/tests-tests.o: In function `test_ecdsa_der_parse':
    /tmp/pip-install-xcal62qa/coincurve/libsecp256k1/src/tests.c:4267: undefined reference to `ECDSA_SIG_get0'
    collect2: error: ld returned 1 exit status
    make: *** [Makefile:969: tests] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xcal62qa/coincurve/setup.py", line 311, in <module>
        **setup_kwargs
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-xcal62qa/coincurve/setup.py", line 197, in run
        subprocess.check_call([MAKE], cwd=build_temp)
      File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
    
    ----------------------------------------
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xcal62qa/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1dl643vp/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-xcal62qa/coincurve/
```

I've tried this from 9.0.0 down to 7.1.0, which 7.1.0 finally ended up working. Now 9.0.0 worked in my virtual environment, but I'm wondering what might have caused this to stop working with the latest versions? Any ideas would be greatly appreciated, thanks.

**Comment by ofek** [comment]
@AnthonyRonning Hello! Did you happen to figure this out?

**Comment by AnthonyRonning** [comment]
@ofek no, I left it at 7.1.0.

**Comment by ofek** [comment]
@AnthonyRonning Can you try again with the latest version?
