### ISSUE TITLE
configure.ac:407: error: AC_PROG_CC cannot be called after AM_PROG_CC_C_O

### ISSUE THREAD

**Issue by youngqqcn** [ofek/coincurve#94]
- CentOS 7
- Python3.6.8
- gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 
- automake:  1.13.4
- autoconf: 2.69

```
[root@node1 pythontests]# sudo pip3 install coincurve
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting coincurve
  Using cached https://files.pythonhosted.org/packages/65/31/9f13921cc7ca27059af4def1a9d1277a6a252dea967b62f9ea05cc2a4115/coincurve-15.0.0.tar.gz
Requirement already satisfied: asn1crypto in /usr/local/lib/python3.6/site-packages (from coincurve)
Requirement already satisfied: cffi>=1.3.0 in /usr/local/lib64/python3.6/site-packages (from coincurve)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.3.0->coincurve)
Installing collected packages: coincurve
  Running setup.py install for coincurve ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-u1e6quzp/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-fb0eljsb-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/__init__.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/_windows_libsecp256k1.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/context.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/ecdsa.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/flags.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/keys.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/types.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/utils.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/py.typed -> build/lib.linux-x86_64-3.6/coincurve
    running build_clib
    configure.ac:407: error: AC_PROG_CC cannot be called after AM_PROG_CC_C_O
    build-aux/m4/ax_prog_cc_for_build.m4:38: AX_PROG_CC_FOR_BUILD is expanded from...
    configure.ac:407: the top level
    autom4te: /usr/bin/m4 failed with exit status: 1
    aclocal: error: echo failed with exit status: 1
    autoreconf: aclocal failed with exit status: 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-u1e6quzp/coincurve/setup.py", line 309, in <module>
        **setup_kwargs
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.6/distutils/command/install.py", line 556, in run
        self.run_command('build')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-u1e6quzp/coincurve/setup.py", line 152, in run
        subprocess.check_call([autogen], cwd=absolute('libsecp256k1'))
      File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-u1e6quzp/coincurve/libsecp256k1/autogen.sh']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-u1e6quzp/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-fb0eljsb-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-u1e6quzp/coincurve/
[root@node1 pythontests]# 



```

**Comment by youngqqcn** [comment]
I upgraded `autoconf` to `2.71`  and upgrade `automake` to ` 1.16.2`, then I successfully installed `coincurve` .

upgrade automake and autoconf on CentOS7: 
> https://www.quyu.net/info/807.html

**Comment by youngqqcn** [comment]
wget https://ftp.gnu.org/gnu/autoconf/autoconf-latest.tar.gz
wget https://ftp.gnu.org/gnu/automake/automake-1.16.2.tar.gz
tar xzf autoconf-latest.tar.gz
tar xzf automake-1.16.2.tar.gz
cd autoconf-2.71
./configure --prefix=/usr
make && make install
cd ..
cd automake-1.16.2
./configure --prefix=/usr
make && make install

**Comment by ofek** [comment]
Thanks!
