### ISSUE TITLE
Error installing with python3.6.9

### ISSUE THREAD

**Issue by maxirodr** [ofek/coincurve#97]
Hello there!

root@scan:/leveldb-1.20/include# pip3 install coincurve
Collecting coincurve
  Using cached https://files.pythonhosted.org/packages/65/31/9f13921cc7ca27059af4def1a9d1277a6a252dea967b62f9ea05cc2a4115/coincurve-15.0.0.tar.gz
Requirement already satisfied: asn1crypto in /usr/lib/python3/dist-packages (from coincurve)
Requirement already satisfied: cffi>=1.3.0 in /usr/local/lib/python3.6/dist-packages (from coincurve)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi>=1.3.0->coincurve)
Building wheels for collected packages: coincurve
  Running setup.py bdist_wheel for coincurve ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qgvqo9t3/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpz0lxusq_pip-wheel- --python-tag cp36:
  /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/context.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/utils.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/_windows_libsecp256k1.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/ecdsa.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/__init__.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/flags.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/keys.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/types.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/py.typed -> build/lib.linux-x86_64-3.6/coincurve
  running build_clib
  /tmp/pip-build-qgvqo9t3/coincurve/libsecp256k1/autogen.sh: 3: /tmp/pip-build-qgvqo9t3/coincurve/libsecp256k1/autogen.sh: autoreconf: not found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-qgvqo9t3/coincurve/setup.py", line 309, in <module>
      **setup_kwargs
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-qgvqo9t3/coincurve/setup.py", line 95, in run
      _bdist_wheel.run(self)
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-qgvqo9t3/coincurve/setup.py", line 152, in run
      subprocess.check_call([autogen], cwd=absolute('libsecp256k1'))
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/tmp/pip-build-qgvqo9t3/coincurve/libsecp256k1/autogen.sh']' returned non-zero exit status 127.

  ----------------------------------------
  Failed building wheel for coincurve

**Comment by maxirodr** [comment]
Done. I've tried in fresh ubuntu 18.xx VPS and i found i didn't have the requirements:

https://pypi.org/project/coincurve/5.0.0/#installation


    build-essential
    automake
    pkg-config
    libtool
    libffi-dev
    libgmp-dev


after install them, i tried again and works OK.
